### ISSUE TITLE
print origins as many lines if there are many

### ISSUE THREAD

**Issue by derhuerst** [k-nut/cspretty#1]
It would be cool to have an option to print a directive's origins as multiple lines, either if there are too many or always.

This will make it easier to quickly scan for a skim for a certain origin.

**Comment by k-nut** [comment]
I have added a multiline version in #3 does that fit your expectations @derhuerst?

**Comment by derhuerst** [comment]
Yes it does! 🎉

**Comment by k-nut** [comment]
closed by #3
